# Generated by Django 3.1.2 on 2020-11-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201115_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
